version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gt-hf-squad"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15xvrs25hhlkm"
s3_prefix = "gt-hf-squad"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Prefix=\"gt-hf-squad\""
